name: PPM
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pandas
  - numpy
  - pytorch
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pip
  - pip:
    - yfinance==0.2.44
    - optuna
    - hydra-core
    - selenium
    - webdriver-manager
    - transformers
    - tf-keras
    - plotly
    - newsapi-python
