stock_info:
  stock_names:
  - AMGN
  - BIIB
  - GILD
  - REGN
  - VRTX
  - MRNA
  - ILMN
  - ALNY
  - INCY
  - TECH
  - EXAS
  - BMRN
  - CRSP
  - FGEN
  - BNTX
  - BLUE
  - BEAM
  - NVAX
  - EXEL
  start_date: '2014-01-01'
  end_date: 2024-8-26
  feature: Close
  features:
  - Close
  - Signal
  - MACD_signal
  - MACD_diff
  - RSI
  - RSI_signal
  - Upper_BB
  - Lower_BB
  training_features:
  - Close
  - MACD
  - Signal
  - MACD_signal
  - MACD_diff
  - TrunOver
  - Amplitude
  - Beta
  - Vix
  - OBV
  - VIX
  - RSI
  - RSI_signal
  - Upper_BB
  - Lower_BB
  - SMA_50
  - SMA_200
  - BTC
  - ETH
optimze:
  num_trail: 100
pretrain:
  epochs: 5000
  lr: 0.001
  batch_size: 1024
  model: ImprovedLSTM
  trained_save_path: pretrained_model_LSTM.pth
  loss_alpha: 0.2
fine_tune:
  epochs: 600
  lr: 0.0003115352184273069
  batch_size: 64
  shuffle: false
  model: TransformerModel
  pre_train: false
  full_feature: false
  auto_feature: true
  trained_model_path: pretrained_model_features.pth
  prediction_file: predictions_TransformerModel
  loss_fun: CustomLossM
  loss_alpha: 0.101821682323762
hyperparameters:
  out_length: 5
  seq_length: 58
model_configs:
  TransformerModel:
    d_model: 64
    nhead: 8
    num_layers: 3
    dropout: 0.2
  TemporalFusionTransformer:
    d_model: 64
    num_heads: 8
    num_layers: 3
    dropout: 0.2
